name: Build

env:
    PHPUNIT_FLAGS: "-v"
    SYMFONY_PHPUNIT_DIR: "$HOME/symfony-bridge/.phpunit"
    # check Symfony versions here https://symfony.com/versions.json
    SYMFONY_LTS: 4.4.*
    SYMFONY_LATEST: 5.2.*
    SYMFONY_DEV: 5.3.*

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
    tests:
        runs-on: ubuntu-latest

        name: "Static checks (PHP ${{ matrix.php }}, Symfony ${{ symfony.php }})"

        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        php: 7.2.9
                        symfony: ${SYMFONY_LTS}
                    -
                        php: 7.3
                        symfony: ${SYMFONY_LATEST}
                    -
                        php: 7.3
                        symfony: ${SYMFONY_DEV}
                    -
                        php: 8.0
                        symfony: ${SYMFONY_LATEST}

        steps:
            -
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global require --no-progress --no-scripts --no-plugins symfony/flex
                    composer config extra.symfony.require "${{ matrix.symfony }}"
                    composer config minimum-stability "dev"
                    composer config prefer-stable true
